import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import { authApi } from "../api/authApi";
import { clearAuthSession, getStoredToken, sessionExpiredEvent, setAuthSession } from "../api/client";
import type { Role, User } from "../types/api";
interface AuthValue { user: User | null; loading: boolean; sessionExpired: boolean; login: (email: string, password: string) => Promise<User>; register: (body: { name: string; email: string; password: string; role: "candidate" | "recruiter" }) => Promise<User>; logout: () => void; updateUser: (user: User) => void; }
const AuthContext = createContext<AuthValue | null>(null);
export function AuthProvider({ children }: { children: ReactNode }) { const [user, setUser] = useState<User | null>(null); const [sessionExpired, setSessionExpired] = useState(false); const [loading, setLoading] = useState(Boolean(getStoredToken())); useEffect(() => { const handleExpired = () => { clearAuthSession(); setUser(null); setSessionExpired(true); }; window.addEventListener(sessionExpiredEvent, handleExpired); if (!getStoredToken()) { setLoading(false); return () => window.removeEventListener(sessionExpiredEvent, handleExpired); } authApi.me().then(({ data }) => setUser(data.user)).catch(() => handleExpired()).finally(() => setLoading(false)); return () => window.removeEventListener(sessionExpiredEvent, handleExpired); }, []); const login = async (email: string, password: string) => { const { data } = await authApi.login({ email, password }); setAuthSession(data.token); setSessionExpired(false); setUser(data.user); return data.user; }; const register = async (body: { name: string; email: string; password: string; role: "candidate" | "recruiter" }) => { const { data } = await authApi.register(body); setAuthSession(data.token); setSessionExpired(false); setUser(data.user); return data.user; }; return <AuthContext.Provider value={{ user, loading, sessionExpired, login, register, logout: () => { clearAuthSession(); setSessionExpired(false); setUser(null); }, updateUser: setUser }}>{children}</AuthContext.Provider>; }
export const useAuth = () => { const context = useContext(AuthContext); if (!context) throw new Error("useAuth must be used inside AuthProvider"); return context; };
export const homeForRole = (role: Role) => role === "admin" ? "/admin" : role === "recruiter" ? "/recruiter" : "/candidate";
