import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes } from "react";
export function Button({ children, variant = "primary", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "ghost" | "danger" }) { return <button className={`button button-${variant}`} {...props}>{children}</button>; }
export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section>; }
export function Badge({ children, tone = "neutral" }: { children: ReactNode; tone?: string }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
export function Input({ label, error, ...props }: InputHTMLAttributes<HTMLInputElement> & { label?: string; error?: string }) { return <label className="field">{label && <span>{label}</span>}<input {...props} />{error && <small className="error-text">{error}</small>}</label>; }
export function Loader() { return <div className="loader" aria-label="Loading" />; }
export function Skeleton({ width = "100%" }: { width?: string }) { return <div className="skeleton" style={{ width }} aria-hidden="true" />; }
export function Empty({ children = "Nothing here yet." }: { children?: ReactNode }) { return <div className="empty">{children}</div>; }
export function ErrorState({ message = "Something went wrong." }: { message?: string }) { return <div className="notice">{message}</div>; }
export function Select({ label, children, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label?: string }) { return <label className="field">{label && <span>{label}</span>}<select {...props}>{children}</select></label>; }
export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="modal-backdrop" role="presentation"><div className="modal" role="dialog" aria-modal="true"><div className="card-heading"><h2>{title}</h2><button className="modal-close" onClick={onClose} aria-label="Close">×</button></div>{children}</div></div>; }
export function ConfirmationDialog({ message, onConfirm, onCancel }: { message: string; onConfirm: () => void; onCancel: () => void }) { return <Modal title="Confirm action" onClose={onCancel}><p>{message}</p><div className="row-actions"><Button variant="ghost" onClick={onCancel}>Cancel</Button><Button variant="danger" onClick={onConfirm}>Confirm</Button></div></Modal>; }
export function Table({ children }: { children: ReactNode }) { return <div className="table-wrap"><table>{children}</table></div>; }
export function Pagination({ page, totalPages, onChange }: { page: number; totalPages: number; onChange: (page: number) => void }) { return <div className="pagination"><Button variant="ghost" disabled={page <= 1} onClick={() => onChange(page - 1)}>Previous</Button><span>Page {page} of {totalPages || 1}</span><Button variant="ghost" disabled={page >= totalPages} onClick={() => onChange(page + 1)}>Next</Button></div>; }
export function Toast({ message, tone = "good" }: { message: string; tone?: "good" | "error" }) { return <div className={`toast toast-${tone}`} role="status">{message}</div>; }
export function PageTitle({ eyebrow, title, children }: { eyebrow?: string; title: string; children?: ReactNode }) { return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div>{children}</div>; }
